### PR TITLE
Extended version support

### PR DESCRIPTION
**Pull request by FaberTheCatgirl**
Added Version Support for Several Titles

### CODE REVIEW

**Comment by FaberTheCatgirl** [comment]
Please note the Appveyor Flag is not an Issue as the Code Compiles and runs fine.

**Comment by FaberTheCatgirl** [comment]
There are also some leftovers from my work on H2AMP, which I had dubbed groundhog at the time prior to the Editing kit release

**Comment by FaberTheCatgirl** [comment]
Error Fixing Before Resubmission of PR

**Comment by FaberTheCatgirl** [comment]
Appveyor CI is not configured for my fork, No Compiling issues/errors are present in the code now and it is all clear to merge

**Comment by FaberTheCatgirl** [comment]
Groundhog StringID Resolver Should be renamed, I will push a correction

**Comment by AnthonyPython** [comment]
ok thanks for fixing the Groundhog stuff.

**Comment by FaberTheCatgirl** [comment]
> ok thanks for fixing the Groundhog stuff.

Thanks for pointing it out to me last week, went right over my head

**Comment by ShellyHerself** [comment]
I was messaged and asked to review this. I personally have no knowledge of TagTool or Halos after 1, so I am not really qualified to comment here. But if I had to add something, it would be that you should set up your editor to respect existing whitespace. The difs are full of whitespaces changes that I can tell github to ignore, but you are still technically modifying these lines and thus messing up the file's history.

**Comment by FaberTheCatgirl** [comment]
> I was messaged and asked to review this. I personally have no knowledge of TagTool or Halos after 1, so I am not really qualified to comment here. But if I had to add something, it would be that you should set up your editor to respect existing whitespace. The difs are full of whitespaces changes that I can tell github to ignore, but you are still technically modifying these lines and thus messing up the file's history.

Interesting, I wasn't aware of that at all, I'll be sure to set up my editor environment to respect the whitespaces next PR

**Comment by Mimickal** [comment]
Why was this PR rejected and marked as spam?

**Comment by NoShotz** [comment]
Because it isn't actually adding support for the different versions of tag caches, it just makes it so that it can recognize them as a compatible cache, but it doesn't add proper tag definitions for all the different versions that he added. At best it will be able to list all the tags, but as soon as you go to edit them, it will likely output an error due to differences in tag definitions between the different versions.

This isn't the first time a half baked pull request or forks were made by Faber to tagtool related repo's, but there is no evidence of it because he keeps deleting his github accounts.

**Comment by AnthonyPython** [comment]
> Because it isn't actually adding support for the different versions of tag caches, it just makes it so that it can recognize them as a compatible cache, but it doesn't add proper tag definitions for all the different versions that he added. At best it will be able to list all the tags, but as soon as you go to edit them, it will likely output an error due to differences in tag definitions between the different versions.
> 
> This isn't the first time a half baked pull request or forks were made by Faber to tagtool related repo's, but there is no evidence of it because he keeps deleting his github accounts.

seems a bit harsh and unfair biased, ideally you'd leave it open and continue to allow more commits and when it's done approve or request other changes.

**Comment by NoShotz** [comment]
> > Because it isn't actually adding support for the different versions of tag caches, it just makes it so that it can recognize them as a compatible cache, but it doesn't add proper tag definitions for all the different versions that he added. At best it will be able to list all the tags, but as soon as you go to edit them, it will likely output an error due to differences in tag definitions between the different versions.
> > This isn't the first time a half baked pull request or forks were made by Faber to tagtool related repo's, but there is no evidence of it because he keeps deleting his github accounts.
> 
> seems a bit harsh and unfair biased, ideally you'd leave it open and continue to allow more commits and when it's done approve or request other changes.

One person wouldn't be able to add support to this many different cache versions in any reasonable amount of time, and it isn't realistically possible to actively support every different version of MCC, and no reason to because everyone that is playing MCC will always be on the latest version of MCC.

Generally you make a pull request when whatever you are trying to commit is fully done, not when you have done the bare minimum to get tagtool to load the cache. Also, this is not a place to chat as everyone that is watching the repo, and any contributors get an email for every single comment made on pull requests.

**Pull request closed without merging**
